name: Signature Verification

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  verify-signatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Verify Signatures
        uses: ICL-ml4csec/signature-trust@v1.0.1
        with:
          repository: ${{ github.repository }}
          branch: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repo-policy: "false:false:false:false:false:false:false"
          deps-policy: "true:true:true:true:true:false:false"
