name: Signature Verification

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  basic-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Basic Security Check
        uses: ICL-ml4csec/signature-trust@v1.1.2
        with:
          repository: ${{ github.repository }}
          branch: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          time-range: "6 months"
          repo-policy: "true:true:true:true:true:false:false"
          deps-policy: "true:true:true:true:true:false:false"
